CREATE DATABASE SCHOOLAPP;

USE SCHOOLAPP;



CREATE TABLE SUBJECTS(
	ID				BIGINT IDENTITY NOT NULL,
	SUBJECT_NAME	VARCHAR(30) NOT NULL,
	SEMESTER		INT NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE STUDENT(
	ID			BIGINT IDENTITY NOT NULL,
	FIRST_NAME	VARCHAR(20) NOT NULL,
	LAST_NAME	VARCHAR(20) NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE TEACHERS(
	ID			BIGINT IDENTITY NOT NULL,
	FIRST_NAME	VARCHAR(20) NOT NULL,
	LAST_NAME	VARCHAR(20) NOT NULL,
	SUBJECT_ID	BIGINT NOT NULL,
	PRIMARY KEY(ID)
);

CREATE TABLE STUDENT_SUBJECTS(
	ID_STUDENT	BIGINT NOT NULL,
	ID_SUBJECT	BIGINT NOT NULL,
);

CREATE  TABLE USERS (
  USERNAME 		VARCHAR(45) NOT NULL ,
  PASSWORD 		VARCHAR(60) NOT NULL ,
  ENABLED 		TINYINT NOT NULL DEFAULT 1 ,
  PRIMARY KEY (USERNAME));

CREATE TABLE USER_ROLES (
  USER_ROLE_ID 	BIGINT IDENTITY NOT NULL,
  USERNAME 		VARCHAR(45) NOT NULL,
  ROLENAME 		VARCHAR(45) NOT NULL,
  PRIMARY KEY (USER_ROLE_ID)
);

ALTER TABLE TEACHERS ADD CONSTRAINT FK_SUBJECT_TEACHERS FOREIGN KEY (SUBJECT_ID) REFERENCES SUBJECTS (ID);
ALTER TABLE USER_ROLES ADD CONSTRAINT FK_USERNAME_IDX FOREIGN KEY (USERNAME) REFERENCES USERS (USERNAME);
ALTER TABLE STUDENT_SUBJECTS ADD CONSTRAINT FK_ID_STUDENT FOREIGN KEY (ID_STUDENT) REFERENCES STUDENT (ID);
ALTER TABLE STUDENT_SUBJECTS ADD CONSTRAINT FK_ID_SUBJECT FOREIGN KEY (ID_SUBJECT) REFERENCES SUBJECTS (ID);
ALTER TABLE STUDENT_SUBJECTS ADD CONSTRAINT PK_STUDENT_SUBJECTS PRIMARY KEY(ID_STUDENT, ID_SUBJECT);


INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('admin', 'password', 1);
INSERT INTO USERS (USERNAME, PASSWORD, ENABLED) VALUES ('user', 'password', 1);
INSERT INTO USER_ROLES (USERNAME, ROLENAME) VALUES ('admin', 'ROLE_ADMIN');
INSERT INTO USER_ROLES (USERNAME, ROLENAME) VALUES ('user', 'ROLE_USER');